### ISSUE TITLE
The Blood Furnace NPC

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Wow-Community-Bugtracker#23]
![image](https://github.com/user-attachments/assets/f6abe33c-bd5b-4711-a19b-7697a7068ad7)
I am alliance and I see the npc 54636 I think that a correction would be needed on the quest givers in this dungeon in relation to the faction.

And at the entrance of the dungeon a piece of chain is displayed but I cannot recover the id of the object because impossible to target

**Comment by Korsar1808** [comment]
FIX
