### ISSUE TITLE
bug quest 72409 (and subsequent)

### ISSUE THREAD

**Issue by brownbr** [Thordekk/Wow-Community-Bugtracker#28]
In Quest 72409, when trying to gather 5 Chewed Piece of Journal, the journals don't seem to spawn, Hoarded Debris dont seem to be accessible.

This is also a general point, because past this moment the entire questline seems to be non-functional. Up to this point it somewhat works (Matthias Shaw's dialogue choices don't seem to work) but after, the quest chain looks incomplete

**Comment by Thordekk** [comment]
Fixed and being fixed entire questline
