### ISSUE TITLE
Dragon Customisation

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Wow-Community-Bugtracker#3]
When playing a previous or new character, the dragon mount skins, accessories and transformations cannot be unlocked by the items you require, and can't be applied to the mounts.
For example - applying - https://www.wowhead.com/spell=394780/deciphering https://www.wowhead.com/item=210536/renewed-proto-drake-embodiment-of-the-blazing will not help unlock the transformation nor allow you too apply it.
![WoWScrnShot_051924_224505](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/394d13d8-dab0-448f-bddd-a7ea3695a596)
![WoWScrnShot_051924_224432](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/d85340e1-fa71-4671-a183-2094a88dae7c)
![WoWScrnShot_051924_224442](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/462c0c8b-4deb-4056-be14-bbf34b213733)
![WoWScrnShot_051924_224449](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/5ee68b15-90f1-4c2f-9847-37a8a56d6fce)

**Comment by Thordekk** [comment]
Fixed
