### ISSUE TITLE
Incorrect Druid Forms & Bugged displays.

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Wow-Community-Bugtracker#4]
Some of the druid races have the incorrect druid forms. For example, the tauren race automatically has the night elf druid forms, and night elf have some tauren druid forms. These need corrected.
Also, in your character profile display, while in cat or bear form, they seem to be completely white. This also needs fixed.

https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/75dcc933-e858-484f-ab3e-79a536a8c2cc

https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/f4225199-72c2-4eb4-820b-53a7d4b6be13

https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/841365a6-9a6c-4aa8-9aa0-280d415b51a3

![449370757_838741174414595_6465963756984178975_n](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/552426c7-9e20-4369-af76-5b771a4ec7f6)
![449329730_337344392759803_1807605826348909689_n](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/eab24c9a-5a94-41ae-bc5d-a916b9ef7e14)

**Comment by Thordekk** [comment]
Fixed
