### ISSUE TITLE
right-beneath-their-eyes quest:59978

### ISSUE THREAD

**Issue by ntlf9t** [Thordekk/Wow-Community-Bugtracker#44]
https://www.wowhead.com/quest=59978/right-beneath-their-eyes

NPCs cannot be triggered

**Comment by Thordekk** [comment]
https://gyazo.com/cbdc9f8a96437851484be4d6f2e8e15b
https://gyazo.com/fdcef2768432dac729a8c5c2455f98f1
https://gyazo.com/7c4e151b159a6124db3709bdb0a12f45

soon i test full exiles  alliance

**Comment by Thordekk** [comment]
phase issue on it

**Comment by Thordekk** [comment]
fixed
