### ISSUE TITLE
Barber Shop issue for Druid & Warlocks.

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Wow-Community-Bugtracker#5]
All customisation options for Druid forms and Warlock pets need unlocked. Also the options that are already unlocked, cannot not be applied to your druid forms/warlock pet. This needs to he looked into and fixed for it all to work.

![WoWScrnShot_051924_224851](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/6bb9dd28-ba8a-4c6d-85bf-cee1099712e7)
![WoWScrnShot_051924_224923](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/69a5b24f-0bf5-430c-ade4-5dfa3ee84028)
![WoWScrnShot_051924_224818](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/d6eb8529-6eec-4066-bae7-ac18a162ccbe)
![WoWScrnShot_070824_173837](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/5f7fb8b0-e0b9-40e3-abec-73fb00c56bc5)
![WoWScrnShot_070824_173817](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/129208594/a75387f0-5a04-4089-a2db-24634c116689)

**Comment by Thordekk** [comment]
Need report the unlock item or spell
