### ISSUE TITLE
Monk & Death Knight talents not working

### ISSUE THREAD

**Issue by mieciuu** [Thordekk/Wow-Community-Bugtracker#57]
1. Monk -> Talent 'Chi Burst' - does nothing, there is animation only
2. Monk Brewmaster -> Two talents that should cause 'Healing Sphere' appear do not make them appear at all (Spirit of the Ox, Gift of the Ox)
3. Blood Death Knight - Talent Gorefiend's Grasp - not working

**Comment by Thordekk** [comment]
add id of spells please

**Comment by Thordekk** [comment]
Monk -> Talent 'Chi Burst' - does nothing, there is animation only
EDIT: FIXED 
please report one spell per report
