### ISSUE TITLE
Death Knight Unholy Talent (194916) Issue

### ISSUE THREAD

**Issue by Bian97** [Thordekk/Wow-Community-Bugtracker#60]
The talent isn't raising the additional skeletal minion.

![image](https://github.com/user-attachments/assets/4b35a725-5cf6-48e3-8797-d354b1bdc6c4)

**Comment by Thordekk** [comment]
Need retail sniff of this spell

**Comment by Bian97** [comment]
Of the Raise Dead? Okay.
All will serve:
https://www.wowhead.com/spell=194916/all-will-serve

Raise dead (46584):
https://www.wowhead.com/wotlk/spell=46584/raise-dead

**Comment by Thordekk** [comment]
Need id of npc skeletal minion so i can fix quick

**Comment by Bian97** [comment]
I don't know if I'm right, but I found it. https://wowhead.com/npc=28878/skeletal-minion

**Comment by Thordekk** [comment]
Fixed and fixed the despawn
