### ISSUE TITLE
Deadmines

### ISSUE THREAD

**Issue by Bian97** [Thordekk/Wow-Community-Bugtracker#62]
The mobs from deadmines are doing overkill hits.
![image](https://github.com/user-attachments/assets/7ee1b54f-ec70-4a7a-9474-25feaa825240)

**Comment by Bian97** [comment]
OBS: I'm level 42 and the mob is 36

**Comment by Thordekk** [comment]
Need sniff retail to get levvel scalings

**Comment by Thordekk** [comment]
If its an elite u need a group

**Comment by Bian97** [comment]
Yes, it was. It just killed me with 1 hit, maybe even with a group it can happen. But I'll try with a group then
