### ISSUE TITLE
Death Knight Unholy bug attack

### ISSUE THREAD

**Issue by Bian97** [Thordekk/Wow-Community-Bugtracker#64]
Sometimes on fighting, my skills don't consume my runes, can be spamed and some of them doesn't work, like Death and Decay and Outbreak. I'm not understanding how, but it happens almost every fight.

To work again, I need to disconnect and connect again.

Bug video: https://drive.google.com/file/d/1BMllNfW04-yClM17ukxi-8G5UUpro-ga/view?usp=sharing

**Comment by Thordekk** [comment]
fixed
