### ISSUE TITLE
Character Customisation

### ISSUE THREAD

**Issue by KKBa20** [Thordekk/Wow-Community-Bugtracker#7]
Unlocking the Dark Ranger Skin, Night Warrior Eyes & Eredar Skin doesn't work and cannot be applied to your character. Needs fixed.

https://www.wowhead.com/achievement=15579/return-to-lordaeron
https://www.wowhead.com/achievement=18938/seeing-red-account
https://www.wowhead.com/spell=285907/blessing-of-the-night-warrior

**Comment by Thordekk** [comment]
What is bug the achievement or quests ?
