### ISSUE TITLE
gameobject not fix

### ISSUE THREAD

**Issue by Steyfix** [Thordekk/Wow-Community-Bugtracker#8]
![image](https://github.com/Thordekk/Wow-Community-Bugtracker/assets/12504219/ab9f2f8c-a485-48c1-9223-8101aa98ba99)
hello after having the quest https://www.wowhead.com/fr/quest=27694/le-bassin-des-larmes#screenshots the gameobject artifacts are spawned but visible only in GM mode and when you interact with it, it does not loot not the quest items

**Comment by Korsar1808** [comment]
FIX
